src/Entity/Company.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="company")
 * @ORM\Entity(repositoryClass="App\Repository\CompanyRepository")
 */

class Company
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;   
    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="NAME")
     */
    private $name;

    /**
    * @Assert\NotBlank(message="ADDRESS")
    * @ORM\Column(type="string", length=50, name="address")
    */
    private $address;
    /**
    * @Assert\NotBlank(message="P_CODE")
    * @ORM\Column(type="string", length=10, name="p_code")
    */
    private $p_code;
    /**
    * @Assert\NotBlank(message="CITY")
    * @ORM\Column(type="string", length=10, name="city")
    */
    private $city;
    /**
    *@ORM\ManyToOne(targetEntity="Countries") */
    private $country;
    /**
    * @Assert\NotBlank(message="EMAIL")
    * @ORM\Column(type="string", length=30, name="email")
    */
    private $email;
    /**
    * @Assert\NotBlank(message="EMAIL")
    * @ORM\Column(type="string", length=128, name="email_pass")
    */
    private $email_pass;
    /**
    * @ORM\Column(type="integer")
    */
    private $email_port;
    /**
    * @ORM\Column(type="string", length=50, name="email_smtp")
    */
    private $email_smtp;
    /**
    * @ORM\Column(type="string", length=4, name="email_certificade")
    */
    private $email_certificade;
    /**
     * @ORM\Column(type="string", length=20, name="telephone", nullable=true)
     */
    private $telephone;
    /**
    * @ORM\Column(type="text", name="meta_keywords", nullable=true)
    */
    private $meta_keywords;
        /**
     * @ORM\Column(type="text", name="meta_description", nullable=true)
     */
    private $meta_description;
    /**
     *@ORM\ManyToOne(targetEntity="Currency") */
    private $currency;
    /**
     * @ORM\Column(type="string", length=50, name="fiscal_number")
     * @Assert\NotBlank(message="FISCAL_NUMBER")
     */
    private $fiscal_number;
    /**
     * @ORM\Column(type="string", length=50, name="coords_google_maps")
     * @Assert\NotBlank(message="COORDS_GOOGLE_MAPS")
     */
    private $coords_google_maps;
    /**
     * @ORM\Column(type="string", length=50, name="google_maps_api_key")
     * @Assert\NotBlank(message="GOOGLE_MAPS_API_KEY")
     */
    private $google_maps_api_key;
    /**
     * @ORM\Column(type="string", name="logo", nullable=true)
     * @Assert\File(mimeTypes={"image/gif", "image/png", "image/jpeg"})
     */
    private $logo;

    /** @ORM\Column(type="string", name="link_my_domain",nullable=true)*/
    private $link_my_domain;
    /** @ORM\Column(type="string", name="link_facebook",nullable=true)*/
    private $link_facebook;
    /** @ORM\Column(type="string", name="link_twitter",nullable=true)*/
    private $link_twitter;
    /** @ORM\Column(type="string", name="link_instagram",nullable=true)*/
    private $link_instagram;
        /** @ORM\Column(type="string", name="link_linken",nullable=true)*/
    private $link_linken;
    /** @ORM\Column(type="string", name="link_pinterest",nullable=true)*/
    private $link_pinterest;
    /** @ORM\Column(type="string", name="link_youtube",nullable=true)*/
    private $link_youtube;
    /** @ORM\Column(type="string", name="link_behance",nullable=true)*/
    private $link_behance;
    /** @ORM\Column(type="string", name="link_snapchat",nullable=true)*/
    private $link_snapchat;

    /** @ORM\Column(type="boolean", name="link_facebook_active", options={"default":0}) */
    private $link_facebook_active = false;
       /** @ORM\Column(type="boolean", name="link_twitter_active", options={"default":0}) */
    private $link_twitter_active = false;
        /** @ORM\Column(type="boolean", name="link_instagram_active", options={"default":0}) */
    private $link_instagram_active = false;
    /** @ORM\Column(type="boolean", name="link_linken_active", options={"default":0}) */
    private $link_linken_active = false;
    /** @ORM\Column(type="boolean", name="link_pinterest_active", options={"default":0}) */
    private $link_pinterest_active = false;
    /** @ORM\Column(type="boolean", name="link_youtube_active",nullable=true)*/
    private $link_youtube_active = false;
    /** @ORM\Column(type="boolean", name="link_behance_active",nullable=true)*/
    private $link_behance_active = false;
    /** @ORM\Column(type="boolean", name="link_snapchat_active",nullable=true)*/
    private $link_snapchat_active = false;

    /** @ORM\Column(type="string", name="stripe_pk",nullable=true)*/
    private $stripe_pk;
        /** @ORM\Column(type="string", name="stripe_sk",nullable=true)*/
    private $stripe_sk;

     /** @ORM\Column(name="close_book_time", type="time", nullable=true) */
    private $close_book_time;

    public function getStripePK()
    {
        return $this->stripe_pk;
    }
    public function setStripePK($stripe_pk)
    {
        $this->stripe_pk = $stripe_pk;
    }

    public function getStripeSK()
    {
        return $this->stripe_sk;
    }
    public function setStripeSK($stripe_sk)
    {
        $this->stripe_sk = $stripe_sk;
    }


    public function getMetaKeywords()
    {
        return $this->meta_keywords;
    }
    public function setMetaKeywords($meta_keywords)
    {
        $this->meta_keywords = $meta_keywords;
    }

    public function getMetaDescription()
    {
        return $this->meta_description;
    }
    public function setMetaDescription($meta_description)
    {
        $this->meta_description = $meta_description;
    }

    public function getEmailPort()
    {
        return $this->email_port;
    }
    public function setEmailPort($email_port)
    {
        $this->email_port = $email_port;
    }

    public function getEmailSmtp()
    {
        return $this->email_smtp;
    }
    public function setEmailSmtp($email_smtp)
    {
        $this->email_smtp = $email_smtp;
    }

    public function getEmailCertificade()
    {
        return $this->email_certificade;
    }
    public function setEmailCertificade($email_certificade)
    {
        $this->email_certificade = $email_certificade;
    }


    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = str_replace("'","’",$name);
    }

    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress($address)
    {
        $this->address = str_replace("'","’",$address);
    }

    public function getCurrency()
    {
        return $this->currency;
    }

    public function setCurrency(Currency $currency)
    {
        $this->currency = $currency;
    }

    public function getPCode()
    {
        return $this->p_code;
    }

    public function setPCode($p_code)
    {
        $this->p_code = str_replace("'","’",$p_code);
    }

    public function getCity()
    {
        return $this->city;
    }

    public function setCity($city)
    {
        $this->city = str_replace("'","’",$city);
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function setCountry(Countries $country)
    {
        $this->country = $country;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = str_replace("'","’",$email);
    }

    public function getEmailPass()
    {
        return $this->email_pass;
    }

    public function setEmailPass($email_pass)
    {
        $this->email_pass = $email_pass;
    }

    public function getTelephone()
    {
        return $this->telephone;
    }

    public function setTelephone($telephone)
    {
        $this->telephone = str_replace("'","’",$telephone);
    }

    public function getFiscalNumber()
    {
        return $this->fiscal_number;
    }

    public function setFiscalNumber($fiscal_number)
    {
        $this->fiscal_number = str_replace("'","’",$fiscal_number);
    }

    public function getCoordsGoogleMaps()
    {
        return $this->coords_google_maps;
    }

    public function setCoordsGoogleMaps($coords_google_maps)
    {
        $this->coords_google_maps = str_replace("'","’",$coords_google_maps);
    }

    public function getGoogleMapsApiKey()
    {
        return $this->google_maps_api_key;
    }

    public function setGoogleMapsApiKey($google_maps_api_key)
    {
        $this->google_maps_api_key = str_replace("'","’",$google_maps_api_key);
    }

    public function getLogo()
    {
        return $this->logo;
    }

    public function setLogo($logo)
    {
        $this->logo = $logo;
        return $this;
    }

    public function getLinkMyDomain()
    {
        return $this->link_my_domain;
    }

    public function setLinkMyDomain($link_my_domain)
    {
        $this->link_my_domain = str_replace("'","’",$link_my_domain);
    }

    public function getLinkFacebook()
    {
        return $this->link_facebook;
    }

    public function setLinkFacebook($link_facebook)
    {
        $this->link_facebook = str_replace("'","’",$link_facebook);
    }

    public function getLinkTwitter()
    {
        return $this->link_twitter;
    }

    public function setLinkTwitter($link_twitter)
    {
        $this->link_twitter = str_replace("'","’",$link_twitter);
    }

    public function getLinkInstagram()
    {
        return $this->link_instagram;
    }

    public function setLinkInstagram($link_instagram)
    {
        $this->link_instagram = str_replace("'","’",$link_instagram);
    }

    public function getLinkLinken()
    {
        return $this->link_linken;
    }

    public function setLinkLinken($link_linken)
    {
        $this->link_linken = str_replace("'","’",$link_linken);
    }

templates/base.html.twig
<!DOCTYPE html>

{% set foo = app.request.locale |split('_') %}
{%set logopath = company.linkMyDomain~asset('upload/gallery/')~company.logo %}

<html lang="{{ foo[0] }}" xml:lang="{{ foo[0] }}" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8">
        <title>{{ company.metaDescription }}</title>
 		<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
		<meta name="keywords" content="{{ company.metaKeywords }}">
 		<meta name="title" content="{{ company.metaDescription }}">
 		<meta name="description" content="{{ company.metaDescription }}">
		<meta name="robots" content="index,nofollow">
       
        <link rel="stylesheet" href="{{ asset('fe/css/bootstrap.min.css') }}">

        <meta name="theme-color" content="#ffffff">
        <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
        <link rel="manifest" href="/favicon/manifest.json">
        <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">

 		<!-- Google / Search Engine Tags -->
        <meta itemprop="name" content="{{ company.metaDescription }}">
        <meta itemprop="description" content="{{ company.metaDescription }}">
        <meta itemprop="image" content="{{ logopath }}">
        
        <!-- Facebook Meta Tags -->
        <meta property="og:url" content="{{ company.linkMyDomain }}">
        <meta property="og:type" content="{{company.name}}">
        <meta property="og:title" content="{{ company.metaDescription }}">
        <meta property="og:description" content="{{ company.metaDescription }}">
        <meta property="og:image" content="{{ logopath }}">
        
        <!-- Twitter Meta Tags -->
        <meta name="twitter:card" content="{{company.linkMyDomain}}/images/banner.jpg">
        <meta name="twitter:title" content="{{ company.metaDescription }}">
        <meta name="twitter:description" content="{{ company.metaDescription }}">
        <meta name="twitter:image" content="{{ logopath }}">
        <link rel="stylesheet" href="{{ asset('font/css/font-awesome.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/home.css') }}">

        <script type="application/ld+json">
            {
              "@context": "http://www.schema.org",
              "@type": "Tours",
              "name": "{{company.name}}",
              "url": "{{company.linkMyDomain}}",
              "logo": "{{logopath}}",
              "image": "{{logopath}}",
              "description": "{{company.metaDescription}}",
              "address": {
                "@type": "PostalAddress",
                "streetAddress": "{{company.address}}",
                "addressLocality": "{{company.city}}",
                "postalCode": "{{company.PCode}}",
                "addressCountry": "Portugal"
              },
              "geo": {
                "@type": "GeoCoordinates",
                "latitude": "{{company.lat}}",
                "longitude": "{{company.long}}"
              },
              "contactPoint": {
                "@type": "ContactPoint",
                "contactType": "customer support",
                "telephone": "{{company.phone}}"
              }
            }
        </script>

        <!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-138976385-1"></script>
        <script>
 	 		window.dataLayer = window.dataLayer || [];
  			function gtag(){dataLayer.push(arguments)}
  			gtag('js', new Date());
			 gtag('config', 'UA-138976385-1');
		</script>
    </head>
    <body>
    	{% include 'taruga/navbar.base.html' %}

		{% include 'taruga/navbarmobile.base.html' %}
		
		{% include 'taruga/banner_0.html' %}

		{% include 'taruga/categ ories.html' %}
{#

		{% include 'taruga/bookings.html' %}
#}
        {% include 'taruga/booking_new.html' %}
		
		{% include 'taruga/footer.html' %}

		{% include 'taruga/modals.html' %}

		<script src="{{ asset('js/home.js') }}"></script>

		{% include 'taruga/javascript.html' %}
    
    </body>
</html>

templates/info.html.twig
<!DOCTYPE html>

{% set foo = app.request.locale |split('_') %}

<html lang="{{ foo[0] }}" xml:lang="{{ foo[0] }}" xmlns="http://www.w3.org/1999/xhtml">

    <head>
 		<meta charset="UTF-8">
        <title>{{ company.metaDescription }}</title>
 		<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
		<meta name="keywords" content="{{ company.metaKeywords }}">
 		<meta name="title" content="{{ company.metaDescription }}">
 		<meta name="description" content="{{ company.metaDescription }}">
		<meta name="robots" content="index,nofollow">
 		
 		<!-- Google / Search Engine Tags -->
        <meta itemprop="name" content="{{ company.metaDescription }}">
        <meta itemprop="description" content="{{ company.metaDescription }}">
        <meta itemprop="image" content="{{ asset('upload/gallery/') }}{{company.logo}}">
        
        <!-- Facebook Meta Tags -->
        <meta property="og:url" content="{{ company.linkMyDomain }}">
        <meta property="og:type" content="website">
        <meta property="og:title" content="{{ company.metaDescription }}">
        <meta property="og:description" content="{{ company.metaDescription }}">
        <meta property="og:image" content="{{ asset('upload/gallery/') }}{{company.logo}}">
        
        <!-- Twitter Meta Tags -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:title" content="{{ company.metaDescription }}">
        <meta name="twitter:description" content="{{ company.metaDescription }}">
        <meta name="twitter:image" content="{{ asset('upload/gallery/') }}{{company.logo}}">
        {% include 'taruga/styles.html' %}
        		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-138976385-1"></script><script>
 	 		window.dataLayer = window.dataLayer || [];
  			function gtag(){dataLayer.push(arguments);}
  			gtag('js', new Date());
			 gtag('config', 'UA-138976385-1');
		</script>
    </head>
    <body>

		{% include 'taruga/navbar.base.html' %}

		{% include 'taruga/navbarmobile.info.html' %}
		
		{% include 'taruga/banner_3.html' %}

		{% include 'taruga/aequipa_iii.html' %}

		{% include 'taruga/aequipa_ii.html' %}

		{% include 'taruga/contatos.html' %}

		{% include 'taruga/ondeestamos.html' %}	
		
		{% include 'taruga/footer.html' %}

		{% include 'taruga/modals.html' %}
		
		{% include 'taruga/javascript.info.html' %}

    </body>
</html>